Frontend/edututor/src/App.jsx, Frontend/edututor/src/Layout/AdminLayout.jsx, Frontend/edututor/src/components/common/Header.jsx, Frontend/edututor/src/components/common/Loading.jsx, Frontend/edututor/src/pages/admin/AdminHome.jsx, Frontend/edututor/src/pages/admin/AdminLogin.jsx, Frontend/edututor/src/pages/main/Home.jsx, Frontend/edututor/src/pages/user/UserJoin.jsx, Frontend/edututor/src/pages/user/UserLogin.jsx
- app.jsx 구조 설정과 관리자 페이지에서 사용할 레이아웃 및 로그인, 회원가입 jsx 파일 생성
- admin 추가
- Loading 컴포넌트 추가
- 회원가입, 로그인 (유저+관리자) jsx 파일 생성
- 관리자 페이지 이동시 5173/admin/xxx 으로 이동하게 중첩 라우팅을 시켜놓음
=> app.jsx 구조 설정 및 관리자 페이지 jsx 생성

Frontend/edututor/src/api/user/school.js, Frontend/edututor/src/components/common/UserStyledComponents.js, Frontend/edututor/src/components/user/UserJoinForm.jsx, Frontend/edututor/src/pages/user/UserJoin.jsx
- 회원가입 화면 작업 
- UserJoin.jsx 생성 및 작업
- UserJoinForm.jsx 생성 및 작업
- school.js 파일 생성 및 학교 정보 가져오기 성공
- UserStyledComponents.js 생성 및 작업
- 서버와 연결 x
- 없음
=> 회원가입 화면 작업 

Backend/edututor/src/main/java/com/tls/edututor/board/category/controller/CategoryController.java, Backend/edututor/src/main/java/com/tls/edututor/board/category/dto/CategoryResult.java, Backend/edututor/src/main/java/com/tls/edututor/board/category/entity/Category.java, Backend/edututor/src/main/java/com/tls/edututor/board/category/repository/CategoryRepository.java, Backend/edututor/src/main/java/com/tls/edututor/board/category/service/CategoryService.java, Backend/edututor/src/main/java/com/tls/edututor/board/category/service/impl/CategoryServiceImpl.java
- 카테고리 서버 구현
- 게시판의 카테고리 서버 구현
- 화이팅...😂
=> 카테고리 서버 구현

Backend/edututor/src/main/java/com/tls/edututor/code/CodeDataInitializer.java, Backend/edututor/src/main/java/com/tls/edututor/school/dto/request/SchoolRequest.java, Backend/edututor/src/main/java/com/tls/edututor/school/entity/School.java, Backend/edututor/src/main/java/com/tls/edututor/school/repository/SchoolRepository.java, Backend/edututor/src/main/java/com/tls/edututor/school/service/SchoolService.java, Backend/edututor/src/main/java/com/tls/edututor/school/service/SchoolServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/user/controller/UserController.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/request/UserTERequest.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/response/AuthUser.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/response/CustomUser.java, Backend/edututor/src/main/java/com/tls/edututor/user/entity/User.java, Backend/edututor/src/main/java/com/tls/edututor/user/jwt/JwtFilter.java, Backend/edututor/src/main/java/com/tls/edututor/user/jwt/LoginFilter.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/CustomUserDetailsService.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/UserService.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/UserServiceImpl.java, Frontend/edututor/src/api/user/school.js, Frontend/edututor/src/api/user/user.js, Frontend/edututor/src/components/common/UserStyledComponents.js, Frontend/edututor/src/components/user/SchoolSearchModal.jsx, Frontend/edututor/src/components/user/UserJoinForm.jsx, Frontend/edututor/src/pages/user/UserJoin.jsx
- 회원가입 페이지 및 Feat/front/join
- 회원가입 페이지 생성
- 서버와 연결 성공
- 회원가입시 학교 정보 입력 성공
- /join 에서 회원가입 가능
- 회원가입 후 이동 처리 x 
- 유효성 체크는 아직 x
=> 회원가입 페이지 및 Feat/front/join

Backend/edututor/src/main/java/com/tls/edututor/code/codedetail/entity/CodeDetail.java, Backend/edututor/src/main/java/com/tls/edututor/code/codegroup/entity/CodeGroup.java, Backend/edututor/src/main/java/com/tls/edututor/code/repository/CodeDetailRepository.java, Backend/edututor/src/main/java/com/tls/edututor/code/repository/CodeGroupRepository.java
- codeRepository 폴더 생성 후 이동
- repository 폴더 생성후 파일 이동
- 없음.
=> codeRepository 폴더 생성 후 이동

Backend/edututor/src/main/java/com/tls/edututor/course/course/controller/CourseController.java, Backend/edututor/src/main/java/com/tls/edututor/course/course/dto/response/CourseNameListResponse.java, Backend/edututor/src/main/java/com/tls/edututor/course/course/dto/response/CourseResponse.java, Backend/edututor/src/main/java/com/tls/edututor/course/course/entity/Course.java, Backend/edututor/src/main/java/com/tls/edututor/course/course/service/CourseService.java, Backend/edututor/src/main/java/com/tls/edututor/course/course/service/impl/CourseServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/course/material/dto/response/MaterialResponse.java, Backend/edututor/src/main/java/com/tls/edututor/course/section/dto/response/SectionResponse.java, Backend/edututor/src/main/java/com/tls/edututor/course/section/entity/Section.java, Backend/edututor/src/main/java/com/tls/edututor/course/unit/UnitService.java, Backend/edututor/src/main/java/com/tls/edututor/course/unit/dto/response/UnitResponse.java, Backend/edututor/src/main/java/com/tls/edututor/course/unit/entity/Unit.java, Backend/edututor/src/main/java/com/tls/edututor/course/unit/service/UnitService.java, Backend/edututor/src/main/java/com/tls/edututor/exam/testpaper/dto/response/TestPaperResponse.java, Backend/edututor/src/main/java/com/tls/edututor/exam/testpaper/entity/TestPaper.java, Backend/edututor/src/main/java/com/tls/edututor/exam/testpaper/service/impl/TestPaperServiceImpl.java, Frontend/edututor/src/App.jsx, Frontend/edututor/src/assets/css/CourseDetailPage.css, Frontend/edututor/src/assets/css/CourseListPage.css, Frontend/edututor/src/pages/admin/CourseCreationPage.jsx, Frontend/edututor/src/pages/admin/CourseDetailPage.jsx, Frontend/edututor/src/pages/admin/CourseEditPage.jsx, Frontend/edututor/src/pages/admin/CourseListPage.jsx, Frontend/edututor/src/pages/admin/TestPaperCreationPage.jsx
- 과정 생성에 대한 CRUD , FRONT/BACK 구현
- Course ** 수정
- 없습니다
=> 과정 생성에 대한 CRUD , FRONT/BACK 구현

Frontend/edututor/src/App.jsx, Frontend/edututor/src/components/board/BoardItem.jsx, Frontend/edututor/src/components/board/BoardList.jsx, Frontend/edututor/src/pages/board/Board.jsx
- 게시판 프론트 틀 구현
- App.jsx 충돌방지
- 감기 안 왔으면
=> 게시판 프론트 틀 구현

Backend/edututor/build.gradle, Backend/edututor/src/main/java/com/tls/edututor/classroom/dto/request/ClassroomRequest.java, Backend/edututor/src/main/java/com/tls/edututor/classroom/entity/Classroom.java, Backend/edututor/src/main/java/com/tls/edututor/classroom/service/ClassroomService.java, Backend/edututor/src/main/java/com/tls/edututor/classroom/service/ClassroomServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/code/service/CodeService.java, Backend/edututor/src/main/java/com/tls/edututor/code/service/CodeServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/common/exception/DuplicateUserException.java, Backend/edututor/src/main/java/com/tls/edututor/common/exception/GlobalExceptionHandler.java, Backend/edututor/src/main/java/com/tls/edututor/school/entity/School.java, Backend/edututor/src/main/java/com/tls/edututor/user/controller/UserController.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/request/UserTERequest.java, Backend/edututor/src/main/java/com/tls/edututor/user/repository/UserRepository.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/UserService.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/UserServiceImpl.java, Frontend/edututor/src/api/user/user.js, Frontend/edututor/src/components/common/UserStyledComponents.js, Frontend/edututor/src/components/user/UserJoinForm.jsx, Frontend/edututor/src/pages/user/UserJoin.jsx
- 회원가입 성공 및 로그인 페이지로 라우팅
- 아직 로그인 x
- 회원가입 유효성 체크 완료
- 아이디 중복 체크 완료
- 회원가입 후 성공되면 /login 으로 라우팅
- 회원가입 후 똑같이 회원가입 시도시 DuplicateUserException 커스텀 예외 발생
- 아직 로그인 페이지 및 로그인 구현 x
=> 회원가입 페이지 및 서버 구현 

Frontend/edututor/src/assets/css/BoardPage.css, Frontend/edututor/src/components/board/BoardItem.jsx, Frontend/edututor/src/components/board/BoardList.jsx, Frontend/edututor/src/pages/board/Board.jsx
- 게시판 프론트엔드 구현
- 공지사항/FAQ/1:1문의 구현
- 다들 건강하자💊
=> 게시판 프론트엔드 구현

Backend/edututor/src/main/java/com/tls/edututor/classroom/service/impl/ClassroomServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/course/course/dto/response/CourseResponse.java, Backend/edututor/src/main/java/com/tls/edututor/exam/exam/controller/ExamController.java, Backend/edututor/src/main/java/com/tls/edututor/exam/exam/service/ExamService.java, Backend/edututor/src/main/java/com/tls/edututor/exam/exam/service/impl/ExamServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/exam/option/dto/response/TestOptionResponse.java, Backend/edututor/src/main/java/com/tls/edututor/exam/question/dto/request/QuestionRegisterRequest.java, Backend/edututor/src/main/java/com/tls/edututor/exam/question/dto/response/TestQuestionResponse.java, Backend/edututor/src/main/java/com/tls/edututor/exam/question/entity/Question.java, Backend/edututor/src/main/java/com/tls/edututor/exam/testpaper/dto/response/StudentTestPaperResponse.java, Backend/edututor/src/main/java/com/tls/edututor/exam/testpaper/service/impl/TestPaperServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/exam/useransewer/dto/request/UserAnswerRequest.java, Backend/edututor/src/main/java/com/tls/edututor/exam/useransewer/entity/UserAnswer.java, Backend/edututor/src/main/java/com/tls/edututor/exam/usertest/dto/request/UserTestRequest.java, Backend/edututor/src/main/java/com/tls/edututor/exam/usertest/entity/UserTest.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/CustomUserDetailsService.java, Frontend/edututor/src/App.jsx, Frontend/edututor/src/assets/css/ExamPage.css, Frontend/edututor/src/assets/css/QuestionList.css, Frontend/edututor/src/assets/css/QuestionNavigation.css, Frontend/edututor/src/assets/css/SubmitButton.css, Frontend/edututor/src/components/exam/QuestionList.jsx, Frontend/edututor/src/components/exam/QuestionNavigation.jsx, Frontend/edututor/src/components/exam/SubmitButton.jsx, Frontend/edututor/src/pages/admin/CourseCreationPage.jsx, Frontend/edututor/src/pages/admin/TestPaperCreationPage.jsx, Frontend/edututor/src/pages/exam/ExamPage.jsx
- 학생 시험 문제 조회 기능 구현 
- 객관식 주관식 나눠서 보여줌
- 문제 등록 방식 일부 수정
- 문제풀이는 오늘 끝내겠습니다,
=> 학생 시험 문제 조회 기능 구현 

Backend/edututor/src/main/java/com/tls/edututor/exam/sharetest/entity/ShareTest.java, Backend/edututor/src/main/java/com/tls/edututor/exam/testpaper/entity/TestPaper.java, Backend/edututor/src/main/java/com/tls/edututor/exam/usertest/entity/UserTest.java
- 공유하기 엔티티 추가
- 공유하기 테이블 추가
- 연관 테이블 구조 수정
- 테이블 구조 수정에 따른 리포트 잘 부탁합니다.
=> 공유하기 엔티티 추가

Backend/edututor/src/main/java/com/tls/edututor/report/repository/UserTestRepository2.java, Backend/edututor/src/main/java/com/tls/edututor/report/service/impl/ReportServiceImpl.java
- UserTestRepository 수정
- 공유 테이블 추가에 따른 repo 수정
- 없음.
=> UserTestRepository2 수정

Backend/edututor/src/main/java/com/tls/edututor/report/dto/response/UserTestResponse2.java, Backend/edututor/src/main/java/com/tls/edututor/report/repository/QuestionRepository2.java, Backend/edututor/src/main/java/com/tls/edututor/report/repository/UserAnswerRepository2.java, Backend/edututor/src/main/java/com/tls/edututor/report/service/impl/ReportServiceImpl.java
- 리포트 상세보기 서버 구현
- 학생 문제, 답안, 성취율 조회
- 없음.
=> 리포트 상세보기 서버 구현

Backend/edututor/src/main/java/com/tls/edututor/report/service/impl/ReportServiceImpl.java
- 리포트 성취율 수정
- 성취율 계산 수정 및 메소드로 분리
- 없음.
=> 리포트 성취율 수정

Backend/edututor/src/main/java/com/tls/edututor/school/entity/School.java, Backend/edututor/src/main/java/com/tls/edututor/user/entity/Refresh.java, Backend/edututor/src/main/java/com/tls/edututor/user/entity/User.java, Backend/edututor/src/main/java/com/tls/edututor/user/exception/DuplicateUserException.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/UserServiceImpl.java, Frontend/edututor/src/api/board/board.js, Frontend/edututor/src/api/exam/ExamApi.js, Frontend/edututor/src/api/user/school.js, Frontend/edututor/src/api/user/user.js, Frontend/edututor/src/pages/admin/CourseCreationPage.jsx, Frontend/edututor/src/pages/admin/CourseDetailPage.jsx, Frontend/edututor/src/pages/admin/CourseEditPage.jsx, Frontend/edututor/src/pages/admin/CourseListPage.jsx, Frontend/edututor/src/pages/admin/MaterialCreationPage.jsx, Frontend/edututor/src/pages/admin/MaterialDetailPage.jsx, Frontend/edututor/src/pages/admin/MaterialEditPage.jsx, Frontend/edututor/src/pages/admin/TestPaperCreationPage.jsx, Frontend/edututor/src/pages/admin/TestPaperDetailPage.jsx, Frontend/edututor/src/pages/course/CourseFilterPage.jsx, Frontend/edututor/src/pages/course/CoursePage.jsx, Frontend/edututor/src/pages/course/CourseRegister.jsx, Frontend/edututor/src/pages/exam/ExamPage.jsx, Frontend/edututor/src/utils/ProtectedRout.jsx
- 요청 axios -> custom axios로 변경
- axios -> custom axios로 변경
- axios.xx() 대신 publicApi.get 혹은 권한 체크 및 access token 만료시 재요청 때문에 publicApi.post로 앞으로 사용 부탁, 
- ProtectedRout에서 사용됨
```javascript
<Route path="classroom" element={
<Suspense fallback={<LoadingSpinner />}>
<ProtectedRout requiredRole="TE">
<Classroom />
</ProtectedRout>
</Suspense>
}>
</Route>
```
=> 요청 axios -> custom axios로 변경

Frontend/edututor/src/App.jsx, Frontend/edututor/src/api/user/user.js, Frontend/edututor/src/components/exam/ExamList.jsx, Frontend/edututor/src/components/exam/ExamShareModal.jsx, Frontend/edututor/src/pages/exam/ExamSharePage.jsx
- 공유하기 모달창 구현
-  app 라우팅 설정
- 공유하기 모달창
- 아직 서버 연결 x
=> 공유하기 모달창 구현

Frontend/edututor/src/api/classroom/classroom.js
- classroom.js 수정
- axios -> public으로 변경
- 없으면 없음.
=> classroom.js 수정

Backend/edututor/src/main/java/com/tls/edututor/security/SecurityConfig.java, Backend/edututor/src/main/java/com/tls/edututor/user/controller/UserController.java, Backend/edututor/src/main/java/com/tls/edututor/user/jwt/JwtFilter.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/impl/RefreshServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/impl/UserServiceImpl.java, Frontend/edututor/src/App.jsx, Frontend/edututor/src/api/axios.js, Frontend/edututor/src/components/common/Header.jsx, Frontend/edututor/src/pages/user/StudentLogin.jsx, Frontend/edututor/src/pages/user/TeacherLogin.jsx, Frontend/edututor/src/utils/AuthContext.jsx
- jwtFilter 시큐리티 컨텍스트 수정
- UserDetailsService 추가
- Authentication에서 classroom 불러오기 가능
- UserServiceImpl 위치 변경
- 로그인.jsx에서 updateUserInfo 수정
- 없음.
=> jwtFilter 시큐리티 컨텍스트 수정

Backend/edututor/src/main/java/com/tls/edututor/user/jwt/JwtFilter.java
- jwtFilter 권한 추가 설정
-  ("ROLE_" + role); 접두사 추가
- 없으면 없음.
=> jwtFilter 권한 추가 설정

Backend/edututor/src/main/java/com/tls/edututor/exam/sharetest/controller/ShareTestController.java, Backend/edututor/src/main/java/com/tls/edututor/exam/sharetest/dto/request/ShareTestRequest.java, Backend/edututor/src/main/java/com/tls/edututor/exam/sharetest/entity/ShareTest.java, Backend/edututor/src/main/java/com/tls/edututor/exam/sharetest/service/ShareTestServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/exam/sharetest/service/impl/ShareTestService.java, Backend/edututor/src/main/java/com/tls/edututor/school/service/SchoolService.java, Backend/edututor/src/main/java/com/tls/edututor/school/service/impl/SchoolServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/user/controller/AuthController.java, Backend/edututor/src/main/java/com/tls/edututor/user/jwt/JwtFilter.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/impl/UserServiceImpl.java, Frontend/edututor/src/api/axios.js, Frontend/edututor/src/api/test-share/testShare.js, Frontend/edututor/src/api/user/user.js, Frontend/edututor/src/components/exam/ExamShareModal.jsx
- 공유하기 모달 수정
- 공유하기 모달에 마감일 추가
- 없음.
=> 공유하기 모달 마감일 추가 

Backend/edututor/src/main/java/com/tls/edututor/course/course/controller/CourseController.java, Backend/edututor/src/main/java/com/tls/edututor/course/course/repository/CourseRepository.java, Backend/edututor/src/main/java/com/tls/edututor/course/course/service/CourseService.java, Backend/edututor/src/main/java/com/tls/edututor/course/course/service/impl/CourseServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/course/courseclassroom/repository/CourseClassroomRepository.java, Frontend/edututor/src/App.jsx, Frontend/edututor/src/assets/css/CoursePage.css, Frontend/edututor/src/components/main/MainSection.jsx, Frontend/edututor/src/pages/course/CourseStudentPage.jsx
- 학생 및 선생 강의 목록 페이지 구현
- 본인 클래스룸의 강의 목록 구현
- 강의 목록 ui 일부 수정
- 없습니다
=> 학생 및 선생 강의 목록 페이지 구현

Frontend/edututor/src/App.jsx, Frontend/edututor/src/Layout/AdminLayout.jsx, Frontend/edututor/src/assets/css/AdminHeader.css, Frontend/edututor/src/assets/css/AdminLayout.css, Frontend/edututor/src/assets/css/AdminSidebar.css, Frontend/edututor/src/assets/css/CourseListPage.css, Frontend/edututor/src/components/admin/AdminHeader.jsx, Frontend/edututor/src/components/admin/AdminSidebar.jsx, Frontend/edututor/src/pages/admin/CourseListPage.jsx
- 관리자 페이지 레이아웃 추가
- 관리자 사이드바 추가
- 관리자 헤더 추가
- 없습니다
=> 관리자 페이지 레이아웃 추가

Backend/edututor/src/main/java/com/tls/edututor/report/controller/ReportController.java, Backend/edututor/src/main/java/com/tls/edututor/report/service/impl/ReportServiceImpl.java, Frontend/edututor/src/App.jsx, Frontend/edututor/src/api/report/report.js, Frontend/edututor/src/assets/css/ReportDetailPage.css, Frontend/edututor/src/components/report/ReportItem.jsx, Frontend/edututor/src/components/report/ReportList.jsx, Frontend/edututor/src/components/report/StudentQuestionStatus.jsx, Frontend/edututor/src/components/report/SummarySection.jsx, Frontend/edututor/src/pages/report/Report.jsx, Frontend/edututor/src/pages/report/ReportDetail.jsx
- 리포트 상세페이지 구현
- 상세페이지 구현
- 없음.
=> 리포트 상세페이지 구현

Frontend/edututor/src/pages/admin/AdminLogin.jsx, Frontend/edututor/src/utils/AuthContext.jsx
- AdminLogin 에서 async await 추가
- AuthContext 에서 관리자 권한 추가 순서 변경
- AdminLogin에 async await 추가
- 없음.
=> AdminLogin 에서 async await 추가

Frontend/edututor/src/components/admin/AdminHeader.jsx, Frontend/edututor/src/utils/AuthContext.jsx
- AuthContext에서 useEffect 의존성 변경
- AuthContext에서 useEffect 의존성 변경 => [userInfo, location.pathname] 두 가지 경우 추가
- 없음.
=> AuthContext에서 useEffect 의존성 변경

Backend/edututor/src/main/java/com/tls/edututor/common/initilizer/DataInitializer.java
- 초기 데이터값 추가
- 게시판 관련 데이터 추가
- 시험 관련 데이터 추가
- 없습니다.
=> 초기 데이터값 추가

Backend/edututor/src/main/java/com/tls/edututor/exam/sharetest/repository/ShareTestRepository.java, Frontend/edututor/package-lock.json, Frontend/edututor/package.json, Frontend/edututor/src/components/material/MaterialPreviewModal.jsx, Frontend/edututor/src/pages/admin/MaterialCreationPage.jsx, Frontend/edututor/yarn.lock
- 형성평가 미리보기 모달 기능 추가
- 모달 관련 모듈 다운
- 없습니다
=> 프론트 형성평가 미리보기 추가

Backend/edututor/src/main/java/com/tls/edututor/report/repository/ShareTestRepository2.java, Backend/edututor/src/main/java/com/tls/edututor/report/repository/UserTestRepository2.java, Backend/edututor/src/main/java/com/tls/edututor/report/service/impl/ReportServiceImpl.java
- 리포트 참여현황 ,성취도 추가
- 리포트 리스트 페이지의 참여현황과 성취도 추가
- 없음.
=> 참여현황, 성취도 추가

Backend/edututor/src/main/java/com/tls/edututor/board/category/entity/Category.java, Backend/edututor/src/main/java/com/tls/edututor/exam/usertest/entity/UserTest.java, Backend/edututor/src/main/java/com/tls/edututor/exam/usertest/service/impl/UserTestServiceImpl.java, Frontend/edututor/src/assets/css/TestPaperCreationPage.css, Frontend/edututor/src/components/common/Footer.jsx, Frontend/edututor/src/pages/admin/CourseCreationPage.jsx, Frontend/edututor/src/pages/admin/CourseDetailPage.jsx, Frontend/edututor/src/pages/admin/TestPaperCreationPage.jsx, Frontend/edututor/src/pages/course/CoursePage.jsx
- 시험지 생성 데이터 추가
- 시험지 제목 및 해설, 지문 추가
- 없습니다.
=> 시험지 생성 데이터 추가

Frontend/edututor/src/assets/css/CourseClassroomEnrollPage.css, Frontend/edututor/src/assets/css/CoursePage.css, Frontend/edututor/src/pages/course/CourseStudentPage.jsx
-  과정 레이아웃 수정
- 양사이드 css 수정
- 없습니다.
=> 과정 레이아웃 수정

Backend/edututor/src/main/java/com/tls/edututor/common/initilizer/DataInitializer.java, Frontend/edututor/src/assets/css/ExamPage.css, Frontend/edututor/src/pages/exam/ExamPage.jsx
- 시험지 데이터 및 페이지 수정
- 시험지 데이터 값 수정
- 시험지 페이지 데이터 수정
- 없습니다.
=> 시험지 데이터 및 페이지 수정

Backend/edututor/src/main/java/com/tls/edututor/report/repository/ShareTestRepository2.java, Backend/edututor/src/main/java/com/tls/edututor/report/repository/UserTestRepository2.java, Backend/edututor/src/main/java/com/tls/edututor/report/service/impl/ReportServiceImpl.java
- 참여현황, 성취도 다시 올림
- 리포트 리스트 참여현황, 성취도 구현
- 없음.
=> 참여현황, 성취도 다시 올림

Frontend/edututor/src/assets/css/ReportDetailPage.css, Frontend/edututor/src/components/common/Header.jsx, Frontend/edututor/src/components/report/StudentQuestionStatus.jsx
- StudentQuestionStatus 수정
- 테이블 문제 수 불러오기 수정
- 없음.
=> StudentQuestionStatus 수정

Backend/edututor/src/main/java/com/tls/edututor/common/initilizer/DataInitializer.java, Backend/edututor/src/main/java/com/tls/edututor/report/dto/response/UserTestResponse2.java, Backend/edututor/src/main/java/com/tls/edututor/report/repository/QuestionRepository2.java, Backend/edututor/src/main/java/com/tls/edututor/report/service/impl/ReportServiceImpl.java
- ReportServiceImpl 수정
- isCorrect 추가
- correctAnswers 제외
- 없음.
=> ReportServiceImpl 수정

Backend/edututor/src/main/java/com/tls/edututor/classroom/controller/ClassroomController.java, Backend/edututor/src/main/java/com/tls/edututor/classroom/service/ClassroomService.java, Backend/edututor/src/main/java/com/tls/edututor/classroom/service/impl/ClassroomServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/security/SecurityConfig.java, Backend/edututor/src/main/java/com/tls/edututor/user/controller/UserController.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/request/UserSURequest.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/response/UserSTResponse.java, Backend/edututor/src/main/java/com/tls/edututor/user/entity/User.java, Backend/edututor/src/main/java/com/tls/edututor/user/repository/UserRepository.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/UserService.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/impl/UserServiceImpl.java, Frontend/edututor/src/api/classroom/classroom.js, Frontend/edututor/src/api/user/user.js, Frontend/edututor/src/components/classroom/CreateStudent.jsx, Frontend/edututor/src/components/classroom/CreateStudentModal.jsx, Frontend/edututor/src/components/classroom/StudentDetailModal.jsx, Frontend/edututor/src/components/classroom/StudentList.jsx, Frontend/edututor/src/components/classroom/StudentListItem.jsx, Frontend/edututor/src/components/exam/ExamShareModal.jsx, Frontend/edututor/src/components/user/UserJoinForm.jsx, Frontend/edututor/src/pages/classroom/Classroom.jsx, Frontend/edututor/src/pages/user/UserJoin.jsx
- 학생 삭제, 수정 구현
- CreateStudentModal css 수정 및
- SecurityConfig 메서드 오타 수정
- StudentDetailModal css 수정
- StudentListItem 학생 수정
- User 엔티티에 updateStudent 추가
- user.js에 update, remove student 추가
- UserController requestMapping 추가
- 없음.
=> 학생 삭제, 수정 구현

Backend/edututor/src/main/java/com/tls/edututor/common/initilizer/DataInitializer.java, Backend/edututor/src/main/java/com/tls/edututor/config/RestTemplateConfig.java, Backend/edututor/src/main/java/com/tls/edututor/exam/useransewer/dto/request/UserAnswerRequest.java, Backend/edututor/src/main/java/com/tls/edututor/exam/usertest/adapter/UserTestAdapter.java, Backend/edututor/src/main/java/com/tls/edututor/exam/usertest/adapter/impl/UserTestAdapterImpl.java, Backend/edututor/src/main/java/com/tls/edututor/exam/usertest/controller/UserTestController.java, Backend/edututor/src/main/java/com/tls/edututor/exam/usertest/dto/request/UserTestRequest.java, Backend/edututor/src/main/java/com/tls/edututor/exam/usertest/service/impl/UserTestServiceImpl.java, Frontend/edututor/src/pages/exam/ExamPage.jsx
- 유저 주관식 답변에 대한 처리 
- 주관식 채점 서비스 추가
- 더미 데이터 문제 주관식 답 추가
- 요청시 무응답일경우 xxx로 대체
- 없습니다.
=> 유저 주관식 답변에 대한 처리 

Backend/edututor/Jenkinsfile, Backend/edututor/build.gradle, Backend/edututor/src/main/java/com/tls/edututor/common/controller/ServerCheckController.java, Backend/edututor/src/main/java/com/tls/edututor/config/JasyptConfig.java
- 빌드 설정 추가 및 암호화 설정
- 서버 정상 실행 컨트롤러 추가
- 젠킨스 설정
- Jastypt 암호화 설정
- 없습니다.
=> 빌드 설정 추가 및 암호화 설정

Backend/edututor/src/main/java/com/tls/edututor/classroom/controller/ClassroomController.java, Backend/edututor/src/main/java/com/tls/edututor/classroom/service/impl/ClassroomServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/exam/sharetest/controller/ShareTestController.java, Backend/edututor/src/main/java/com/tls/edututor/exam/sharetest/repository/ShareTestRepository.java, Backend/edututor/src/main/java/com/tls/edututor/security/SecurityConfig.java, Backend/edututor/src/main/java/com/tls/edututor/user/controller/UserController.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/response/UserSTResponse.java, Frontend/edututor/src/api/user/school.js, Frontend/edututor/src/components/common/Header.jsx, Frontend/edututor/src/components/exam/ExamShareModal.jsx, Frontend/edututor/src/pages/course/CoursePage.jsx, Frontend/edututor/src/pages/user/UserJoin.jsx, Frontend/edututor/src/utils/AuthContext.jsx
- 헤더 css 및 시험공유 모달 수정
- 헤더 서브메뉴 제거
- 이미 공유된 학생 공유 해제 가능 (아직 수정은 서버에서 구현 x)
- 이미 등록된 학생 표시
- 없음.
=> 헤더 css 및 시험공유 모달 수정

Frontend/edututor/src/components/exam/ExamShareModal.jsx
- ExamShareModal fetchAllStudent 수정
- fetchAllStudent 
```javascript
const fetchAllStudent = async () => {
try {
const userInfo = JSON.parse(localStorage.getItem('info'));
const result = await getAllStudent(userInfo.classroom.id);
const key = Object.keys(result.data)[0]; => 이 부분 추가
setStudentInfo(result.data[key] || []);
} catch (error) {
console.error('Failed to fetch students', error);
}
}
```
- 없음.
=> ExamShareModal fetchAllStudent 수정

Frontend/edututor/src/App.jsx, Frontend/edututor/src/assets/css/NoticePage.css, Frontend/edututor/src/components/board/NoticeItem.jsx, Frontend/edututor/src/components/board/NoticeList.jsx, Frontend/edututor/src/components/common/Header.jsx, Frontend/edututor/src/components/common/Pagination.jsx, Frontend/edututor/src/components/report/ReportList.jsx, Frontend/edututor/src/pages/board/Board.jsx, Frontend/edututor/src/pages/board/Faq.jsx, Frontend/edututor/src/pages/board/Inquiry.jsx, Frontend/edututor/src/pages/board/Notice.jsx, Frontend/edututor/src/pages/report/Report.jsx
- 고객센터 프론트 분리
- 공지사항 Notice.jsx 외 여러 개 추가
- 공지사항 디테일 불러오기
- Faq, 1:1 마저 분리하기
=> 고객센터 프론트 분리

Backend/edututor/src/main/java/com/tls/edututor/classroom/dto/response/ClassroomResponse.java, Backend/edututor/src/main/java/com/tls/edututor/school/dto/response/SchoolResponse.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/impl/CustomOAuthSuccessHandler.java, Frontend/edututor/src/pages/user/OAuthSuccess.jsx
- parsing문제 해결 및 classroom response 생성
```javascript
useEffect(() => {
const encodedData = searchParams.get('data');
if (encodedData) {
try {
const base64 = encodedData.replace(/-/g, '+').replace(/_/g, '/');
const decodedString = new TextDecoder('utf-8').decode(Uint8Array.from(atob(base64), c => c.charCodeAt(0)));
localStorage.setItem('info', decodedString);
dispatchEvent(new Event('auth-update'));
} catch (error) {
console.error('Decoding failed:', error);
}
}
navigate('/');
}, []);
```
- 없음.
=> parsing문제 해결 및 classroom response 생성

Backend/edututor/src/main/java/com/tls/edututor/board/board/dto/response/BoardResponse.java, Backend/edututor/src/main/java/com/tls/edututor/board/board/repository/BoardRepository.java, Backend/edututor/src/main/java/com/tls/edututor/board/board/service/impl/BoardServiceImpl.java, Frontend/edututor/src/App.jsx, Frontend/edututor/src/assets/css/NoticeDetailPage.css, Frontend/edututor/src/components/board/NoticeItem.jsx, Frontend/edututor/src/components/board/NoticeList.jsx, Frontend/edututor/src/components/common/Header.jsx, Frontend/edututor/src/pages/board/Notice.jsx, Frontend/edututor/src/pages/board/NoticeDetail.jsx
- 게시판 페이지 분리
- 게시판 공지사항 디테일 페이지 분리
- BoardDetail.jsx 추가
- 없음
=> 게시판 페이지 분리

Backend/edututor/src/main/java/com/tls/edututor/board/board/dto/response/BoardResponse.java, Frontend/edututor/src/api/board/category.js, Frontend/edututor/src/assets/css/BoardPage.css, Frontend/edututor/src/assets/css/FaqPage.css, Frontend/edututor/src/components/board/BoardList.jsx, Frontend/edututor/src/components/board/Category.jsx, Frontend/edututor/src/components/board/FaqItem.jsx, Frontend/edututor/src/components/board/FaqList.jsx, Frontend/edututor/src/components/board/NoticeItem.jsx, Frontend/edututor/src/pages/board/Faq.jsx, Frontend/edututor/src/pages/board/NoticeDetail.jsx
- 고객센터 FAQ 화면 분리
- Faq.jsx / FaqList.jsx / FaqItem 추가
- 없음.
=> FAQ 화면 분리 및 수정

Backend/edututor/src/main/java/com/tls/edututor/common/initilizer/DataInitializer.java, Frontend/edututor/src/assets/css/CoursePage.css, Frontend/edututor/src/pages/course/CoursePage.jsx
- 데이터베이스 초기화 및 과정 css 수정
- 데이터베이스 초기화 전체 초기화
- 없습니다
=> 데이터베이스 초기화 및 과정 css 수정

Backend/edututor/src/main/java/com/tls/edututor/report/service/impl/ReportServiceImpl.java
- 리포트 성취도 소수점 버림
- 소수점 버리기
- 없음.
=> 리포트 성취도 소수점 버림

Backend/edututor/src/main/java/com/tls/edututor/issue/controller/IssueController.java, Backend/edututor/src/main/java/com/tls/edututor/issue/dto/request/IssueRegisterRequest.java, Backend/edututor/src/main/java/com/tls/edututor/issue/entity/Issue.java, Backend/edututor/src/main/java/com/tls/edututor/issue/repository/IssueRepository.java, Backend/edututor/src/main/java/com/tls/edututor/issue/service/IssueService.java, Backend/edututor/src/main/java/com/tls/edututor/issue/service/impl/IssueServiceImpl.java, Frontend/edututor/src/App.jsx, Frontend/edututor/src/assets/css/IssueListPage.css, Frontend/edututor/src/assets/css/IssueModal.css, Frontend/edututor/src/assets/css/TestPreviewModal.css, Frontend/edututor/src/components/admin/AdminSidebar.jsx, Frontend/edututor/src/components/exam/TestPreviewModal.jsx, Frontend/edututor/src/components/issue/IssueModal.jsx, Frontend/edututor/src/pages/admin/IssueListPage.jsx
- 문제 신고 기능 구현
- 문제 신고하기 로직 및 ui 구현
- 문제 리스트 구현
- 없습니다.
=> 문제 신고 기능 구현

Backend/edututor/src/main/java/com/tls/edututor/board/answer/entity/Answer.java, Backend/edututor/src/main/java/com/tls/edututor/board/board/entity/Board.java, Backend/edututor/src/main/java/com/tls/edututor/board/category/entity/Category.java, Backend/edututor/src/main/java/com/tls/edututor/classroom/entity/Classroom.java, Backend/edututor/src/main/java/com/tls/edututor/code/codedetail/entity/CodeDetail.java, Backend/edututor/src/main/java/com/tls/edututor/code/codegroup/entity/CodeGroup.java, Backend/edututor/src/main/java/com/tls/edututor/course/course/entity/Course.java, Backend/edututor/src/main/java/com/tls/edututor/course/course/entity/CourseClassroom.java, Backend/edututor/src/main/java/com/tls/edututor/course/material/entity/Material.java, Backend/edututor/src/main/java/com/tls/edututor/course/section/entity/Section.java, Backend/edututor/src/main/java/com/tls/edututor/course/unit/entity/Unit.java, Backend/edututor/src/main/java/com/tls/edututor/exam/option/entity/Option.java, Backend/edututor/src/main/java/com/tls/edututor/exam/question/entity/Question.java, Backend/edututor/src/main/java/com/tls/edututor/exam/testpaper/entity/TestPaper.java, Backend/edututor/src/main/java/com/tls/edututor/exam/useransewer/entity/UserAnswer.java, Backend/edututor/src/main/java/com/tls/edututor/exam/usertest/entity/UserTest.java, Backend/edututor/src/main/java/com/tls/edututor/issue/entity/Issue.java, Backend/edututor/src/main/java/com/tls/edututor/school/entity/School.java, Frontend/edututor/package-lock.json, Frontend/edututor/yarn.lock
- entity별 is_deleted 옵션추가
- @SQLDelete(sql = "update user u set u.is_deleted = true where u.id = ?") 추가
- @SQLRestriction("is_deleted = false") 추가
- 없습니다.
=> entity별 is_deleted 옵션추가

Frontend/edututor/src/components/main/CourseSection.jsx
- CourseSection css 수정 및 리펙토링
- 반응형으로 변경
- 없음.
=> CourseSection css 수정 및 리펙토링

Frontend/edututor/src/components/common/Header.jsx, Frontend/edututor/src/components/user/TeacherUpdateFormModal.jsx
- TeacherUpdateFormModal useEffect 수정
- Header에서 사람 클릭시 유저정보 넘김
- TeacherUpdateFormModal useEffect에서 유저 정보 세팅
- 없음
=> TeacherUpdateFormModal useEffect 수정

Backend/edututor/src/main/java/com/tls/edututor/common/initilizer/DataInitializer.java, Frontend/edututor/src/assets/css/CoursePage.css, Frontend/edututor/src/pages/course/CourseClassroomEnrollPage.jsx, Frontend/edututor/src/pages/course/CoursePage.jsx, Frontend/edututor/src/pages/course/CourseStudentPage.jsx
- 강의 ui 일부 수정
- 강의 ui 기능적 추가 및 데이터 변경
- 없습니다.
=> 강의 ui 일부 수정

Frontend/edututor/src/App.jsx, Frontend/edututor/src/components/admin/AdminLoginForm.jsx, Frontend/edututor/src/components/common/UserStyledComponents.js, Frontend/edututor/src/components/user/UserJoinForm.jsx, Frontend/edututor/src/pages/admin/AdminLogin.jsx, Frontend/edututor/src/pages/user/TeacherLogin.jsx
- login css 수정
- required 추가
- 없음.
=> login css 수정

Backend/edututor/src/main/java/com/tls/edututor/report/service/impl/ReportServiceImpl.java, Frontend/edututor/src/assets/css/CoursePage.css, Frontend/edututor/src/pages/course/CourseClassroomEnrollPage.jsx, Frontend/edututor/src/pages/course/CoursePage.jsx, Frontend/edututor/src/pages/course/CourseStudentPage.jsx
- 강의등록 및 강의 페이지 course 등록 수정
- 클래스룸에 강의 등록시 강의 미리보기 추가
- swal 및 css 수정 부탁드립니다.
=> 강의등록 및 강의 페이지 course 등록 수정

Backend/edututor/src/main/java/com/tls/edututor/board/answer/entity/Answer.java, Backend/edututor/src/main/java/com/tls/edututor/board/answer/repository/AnswerRepository.java, Backend/edututor/src/main/java/com/tls/edututor/board/board/controller/BoardController.java, Backend/edututor/src/main/java/com/tls/edututor/board/board/dto/response/BoardResponse.java, Backend/edututor/src/main/java/com/tls/edututor/board/board/entity/Board.java, Backend/edututor/src/main/java/com/tls/edututor/board/board/service/BoardService.java, Backend/edututor/src/main/java/com/tls/edututor/board/board/service/impl/BoardServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/report/service/impl/ReportServiceImpl.java, Frontend/edututor/src/api/board/board.js, Frontend/edututor/src/assets/css/InquiryDetailPage.css, Frontend/edututor/src/assets/css/NoticePage.css, Frontend/edututor/src/components/board/InquiryForm.jsx, Frontend/edututor/src/components/board/InquiryItem.jsx, Frontend/edututor/src/pages/board/InquiryDetail.jsx
- 1대1 문의 답변 가져오기
- 답변이 있는 경우 상태 변경
- inquiry 관련 화면 추가
- boardService 수정
- 없음.
=> feat : 1대1 문의 답변 추가

Frontend/edututor/src/api/board/board.js, Frontend/edututor/src/assets/css/ReportDetailPage.css, Frontend/edututor/src/components/report/StudentQuestionStatus.jsx, Frontend/edututor/src/pages/board/InquiryDetail.jsx
- 리포트 상세페이지 정답 여부 수정
- 기존 유저 답안과 색상으로 표시 -> O/X로 표시
- 없음.
=> 리포트 정답 여부 수정

Backend/edututor/src/main/java/com/tls/edututor/exam/sharetest/controller/ShareTestController.java, Backend/edututor/src/main/java/com/tls/edututor/exam/sharetest/dto/request/ShareTestRequest.java, Backend/edututor/src/main/java/com/tls/edututor/exam/sharetest/service/ShareTestServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/exam/sharetest/service/impl/ShareTestService.java, Frontend/edututor/src/api/test-share/testShare.js, Frontend/edututor/src/components/admin/AdminUserList.jsx, Frontend/edututor/src/components/common/Header.jsx, Frontend/edututor/src/components/exam/ExamShareModal.jsx, Frontend/edututor/src/utils/AuthContext.jsx
- 공유하기 취소 가능
- deadline 제거
- 중복 공유 제거
- 취소 가능
- 없으면 없음.
=> 공유하기 취소 가능

Frontend/edututor/src/assets/css/CourseClassroomEnrollPage.css, Frontend/edututor/src/assets/css/CoursePage.css, Frontend/edututor/src/components/common/Header.jsx, Frontend/edututor/src/components/main/CourseSection.jsx, Frontend/edututor/src/components/main/InfoSection.jsx, Frontend/edututor/src/pages/course/CourseClassroomEnrollPage.jsx, Frontend/edututor/src/pages/course/CoursePage.jsx
- course 관련 css 수정
- 메인의 course 화살표 수정
- course 등록 css 수정
- 없으면 없음.
=> course 관련 css 수정

Backend/edututor/src/main/java/com/tls/edututor/classroom/controller/ClassroomController.java, Backend/edututor/src/main/java/com/tls/edututor/classroom/service/impl/ClassroomServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/user/controller/UserController.java, Backend/edututor/src/main/java/com/tls/edututor/user/entity/User.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/UserService.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/impl/UserServiceImpl.java, Frontend/edututor/src/api/user/user.js, Frontend/edututor/src/components/classroom/StudentDetailModal.jsx, Frontend/edututor/src/components/main/CourseSection.jsx, Frontend/edututor/src/components/user/OAuthUserJoinForm.jsx, Frontend/edututor/src/components/user/TeacherUpdateFormModal.jsx, Frontend/edututor/src/components/user/UserJoinForm.jsx, Frontend/edututor/src/pages/admin/CourseListPage.jsx, Frontend/edututor/src/pages/admin/IssueListPage.jsx, Frontend/edututor/src/pages/admin/MaterialDetailPage.jsx, Frontend/edututor/src/pages/admin/MaterialEditPage.jsx, Frontend/edututor/src/pages/admin/TestPaperDetailPage.jsx, Frontend/edututor/src/pages/board/InquiryDetail.jsx, Frontend/edututor/src/pages/board/NoticeDetail.jsx, Frontend/edututor/src/pages/course/CoursePage.jsx, Frontend/edututor/src/pages/course/CourseStudentPage.jsx, Frontend/edututor/src/pages/exam/ExamPage.jsx, Frontend/edututor/src/pages/material/MaterialDetailStudentPage.jsx, Frontend/edututor/src/pages/user/UserJoin.jsx
- 회원가입 및 선생님 유저 수정
- 회원가입 및 선생님 유저 수정
- loading 문구 Loading 컴포넌트로 변경
- 없으면 없음.
=> 회원가입 및 선생님 유저 수정

Frontend/edututor/src/pages/course/CourseStudentPage.jsx
- 학생 course 페이지 css 수정
-  학생 course 페이지 css 수정
- 없으면 없음.
=> 학생 course 페이지 css 수정

Backend/edututor/src/main/java/com/tls/edututor/classroom/service/impl/ClassroomServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/security/SecurityConfig.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/impl/MailServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/impl/UserServiceImpl.java, Frontend/edututor/src/components/main/CourseSection.jsx, Frontend/edututor/src/components/user/FindLoginInfoModal.jsx
-  CourseSection 드래그랑 필터 합침
- 아아디, 비밀번호 찾기 구현
- CourseSection 드래그랑 필터 합침
- 없음.
=> CourseSection 드래그랑 필터 합침

Backend/edututor/src/main/java/com/tls/edututor/config/RedisConfig.java, Backend/edututor/src/main/java/com/tls/edututor/security/SecurityConfig.java, Backend/edututor/src/main/java/com/tls/edututor/user/controller/UserController.java, Backend/edututor/src/main/java/com/tls/edututor/user/controller/UserStatisticsController.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/response/DailySignupStats.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/response/MonthlySignupStats.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/response/TeacherStudentCount.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/response/UserDeletedStats.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/response/UserDeletedStatsInterface.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/response/UserSignupStats.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/response/UserStatisticsResponse.java, Backend/edututor/src/main/java/com/tls/edututor/user/dto/response/YearlySignupStats.java, Backend/edututor/src/main/java/com/tls/edututor/user/repository/UserRepository.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/UserService.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/UserStatisticsService.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/impl/UserServiceImpl.java, Backend/edututor/src/main/java/com/tls/edututor/user/service/impl/UserStatisticsServiceImpl.java, Frontend/edututor/package.json, Frontend/edututor/src/App.jsx, Frontend/edututor/src/api/user/user.js, Frontend/edututor/src/components/admin/AdminSidebar.jsx, Frontend/edututor/src/components/admin/AdminUserList.jsx, Frontend/edututor/src/components/admin/AdminUserStatistic.jsx, Frontend/edututor/src/utils/AuthContext.jsx, Frontend/edututor/src/utils/ProtectedRoute.jsx
- 사용자 현황 통계, 선생님 탈퇴시 학생도 탈퇴
- 사용자 현황 통계, 선생님 탈퇴시 학생도 탈퇴
- 없음.
=> 사용자 현황 통계, 선생님 탈퇴시 학생도 탈퇴

Frontend/edututor/src/components/common/AdminStyledComponent.jsx, Frontend/edututor/src/pages/admin/CourseCreationPage.jsx, Frontend/edututor/src/pages/admin/TestPaperCreationPage.jsx
- test page, create test paper css 수정
- create-course css 수정
- test-page css 수정
- 없으면 없음.
=> test page, create test paper css 수정

Frontend/edututor/src/App.jsx, Frontend/edututor/src/components/common/Header.jsx, Frontend/edututor/src/pages/user/UserLogin.jsx
- 로그인 css 수정
- 헤더, 푸터 포함
- container fix에서 변경
- 없음.
=> 로그인 css 수정

Backend/edututor/src/main/java/com/tls/edututor/board/board/service/impl/BoardServiceImpl.java
- BoardServiceImpl 수정
- - getBoardsByCategory 에서 authentication null 예외처리
- 없음.
=> BoardServiceImpl 수정

Frontend/edututor/src/components/main/CourseSection.jsx, Frontend/edututor/src/pages/admin/AdminLogin.jsx
#
- CourseSection 예외처리, admin 로그인 후 localStorage 삭제
- filteredCourses에서 값이 있을때 보여주기
- admin 로그인 후 localStorage 삭제, 그래야 teacher로 로그인 -> admin 로그인 -> localStorage에 정보는 남아있어서 다시 홈으로 이동시 해당 선생 계정으로 로그인 되어있지만 쿠키가 바뀌어서 courseSection을 못불러옴
- 다시 로그인 하도록 info 제거
- 없음.
=> CourseSection 예외처리, admin 로그인 후 localStorage 삭제

Frontend/edututor/src/pages/board/Inquiry.jsx
- Inquiry 비회원이면 글 못쓰게
- userRole에 따른 return
- 없음.
=> Inquiry 비회원이면 글 못쓰게

Frontend/edututor/src/components/common/Header.jsx
-  header css 수정
- 햄버거에서 로그아웃 버튼 위치 조절
- 햄버거 먹고싶다.
- 없음.
=> header css 수정

Frontend/edututor/src/pages/admin/MaterialCreationPage.jsx, Frontend/edututor/src/pages/admin/MaterialEditPage.jsx, Frontend/edututor/src/pages/user/UserLogin.jsx
- 학습자료 등록, 수정 css 수정
- 학습자료 등록, 수정 css 수정
- 이제 그만...
=> 학습자료 등록, 수정 css 수정
